package org.objectweb.hello_world_doc_lit;

import javax.xml.ws.WebFault;
import org.objectweb.hello_world_doc_lit.types.FaultDetail;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "faultDetail", targetNamespace = "http://objectweb.org/hello_world_doc_lit/types")
public class PingMeFault extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetail faultInf;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PingMeFault(String message, FaultDetail faultInfo) {
        super(message);
        this.faultInf = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public PingMeFault(String message, FaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInf = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.objectweb.hello_world_doc_lit.types.FaultDetail
     */
    public FaultDetail getFaultInfo() {
        return faultInf;
    }

}
