package org.objectweb.hello_world_doc_lit;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0-11/04/2005 09:41
 * AM(bbissett) Generated source version: 2.0
 */
@WebService(name = "Greeter", 
            targetNamespace = "http://objectweb.org/hello_world_doc_lit", 
            wsdlLocation = "hello_world_doc_lit.wsdl")
public interface Greeter {

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType", targetNamespace = "http://objectweb.org/hello_world_doc_lit/types")
    @RequestWrapper(localName = "sayHi", 
                    targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                    className = "org.objectweb.hello_world_doc_lit.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", 
                     targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                     className = "org.objectweb.hello_world_doc_lit.types.SayHiResponse")
    String sayHi();

    /**
     * @param requestType
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType", targetNamespace = "http://objectweb.org/hello_world_doc_lit/types")
    @RequestWrapper(localName = "greetMe", 
                    targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                    className = "org.objectweb.hello_world_doc_lit.types.GreetMe")
    @ResponseWrapper(localName = "greetMeResponse", 
                     targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                     className = "org.objectweb.hello_world_doc_lit.types.GreetMeResponse")
    String greetMe(
                   @WebParam(name = "requestType", 
                             targetNamespace = "http://objectweb.org/hello_world_doc_lit/types")
                   String requestType);

    /**
     * @param requestType
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", 
                    targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                    className = "org.objectweb.hello_world_doc_lit.types.GreetMeOneWay")
    void greetMeOneWay(
                              @WebParam(name = "requestType", 
                                        targetNamespace = "http://objectweb.org/hello_world_doc_lit/types")
                              String requestType);

    /**
     * @throws PingMeFault
     */
    @WebMethod
    @RequestWrapper(localName = "pingMe", 
                    targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                    className = "org.objectweb.hello_world_doc_lit.types.PingMe")
    @ResponseWrapper(localName = "pingMeResponse", 
                     targetNamespace = "http://objectweb.org/hello_world_doc_lit/types", 
                     className = "org.objectweb.hello_world_doc_lit.types.PingMeResponse")
    void pingMe() throws PingMeFault;

}
