
package org.objectweb.hello_world_doc_wrapped_bare;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.objectweb.hello_world_doc_wrapped_bare.types.BareDocumentResponse;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 *
 */
@WebService(name = "Greeter",
            targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare",
            wsdlLocation = "hello_world_doc_wrapped_bare.wsdl")
public interface Greeter {


    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType",
               targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
    @RequestWrapper(localName = "sayHi",
                    targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                    className = "org.objectweb.hello_world_doc_wrapped_bare.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse",
                     targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                     className = "org.objectweb.hello_world_doc_wrapped_bare.types.SayHiResponse")
    String sayHi();

    /**
     *
     * @param requestType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType",
               targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
    @RequestWrapper(localName = "greetMe",
                    targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                    className = "org.objectweb.hello_world_doc_wrapped_bare.types.GreetMe")
    @ResponseWrapper(localName = "greetMeResponse",
                     targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                     className = "org.objectweb.hello_world_doc_wrapped_bare.types.GreetMeResponse")
    String greetMe(
        @WebParam(name = "requestType",
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
        String requestType);

    /**
     *
     * @param requestType
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType",
               targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
    @RequestWrapper(localName = "greetMeSometime",
                    targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                    className = "org.objectweb.hello_world_doc_wrapped_bare.types.GreetMeSometime")
    @ResponseWrapper(localName = "greetMeSometimeResponse",
                     targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                     className = "org.objectweb.hello_world_doc_wrapped_bare.types.GreetMeSometimeResponse")
    String greetMeSometime(
        @WebParam(name = "requestType",
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
        String requestType);

    /**
     *
     * @param requestType
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "greetMeOneWay",
                    targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                    className = "org.objectweb.hello_world_doc_wrapped_bare.types.GreetMeOneWay")
    void greetMeOneWay(
        @WebParam(name = "requestType",
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
        String requestType);

    /**
     *
     * @param faultType
     * @throws BadRecordLitFault
     * @throws NoSuchCodeLitFault
     */
    @WebMethod
    @RequestWrapper(localName = "testDocLitFault",
                    targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                    className = "org.objectweb.hello_world_doc_wrapped_bare.types.TestDocLitFault")
    @ResponseWrapper(localName = "testDocLitFaultResponse",
                     targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                     className = "org.objectweb.hello_world_doc_wrapped_bare.types.TestDocLitFaultResponse")
    void testDocLitFault(
        @WebParam(name = "faultType",
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
        String faultType)
        throws BadRecordLitFault, NoSuchCodeLitFault;


    /**
     *
     * @param in
     * @return
     *     returns org.objectweb.hello_world_doc_wrapped_bare.types.BareDocumentResponse
     */
    @WebMethod(action = "http://objectweb.org/hello_world_doc_wrapped_bare/testDocLitBare")
    @WebResult(name = "BareDocumentResponse",
               targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
               partName = "out")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    BareDocumentResponse testDocLitBare(
        @WebParam(name = "BareDocument",
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types",
                  partName = "in")
        String in);

}
