
package org.objectweb.hello_world_doc_wrapped_bare;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SOAPService_Test1", 
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare", 
                  wsdlLocation = "hello_world_doc_wrapped_bare.wsdl")
public class SOAPServiceTest1
    extends Service {

    private  static final URL WSDL_LOCATION;
    private  static final QName SOAPSERVICETEST1 = 
        new QName("http://objectweb.org/hello_world_doc_wrapped_bare", "SOAPService_Test1");
    private  static final QName SOAPPORTTEST1 = 
        new QName("http://objectweb.org/hello_world_doc_wrapped_bare", "SoapPort_Test1");
    private  static final QName SOAPPORTTEST2 =
        new QName("http://objectweb.org/hello_world_doc_wrapped_bare", "SoapPort_Test2");

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Project/jaxws-2.0ea2/bin/hello_world_doc_wrapped_bare.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SOAPServiceTest1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPServiceTest1() {
        super(WSDL_LOCATION, SOAPSERVICETEST1);
    }

    /**
     * 
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort_Test1")
    public Greeter getSoapPortTest1() {
        return (Greeter)super.getPort(SOAPPORTTEST1, Greeter.class);
    }

    /**
     * 
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort_Test2")
    public Greeter getSoapPortTest2() {
        return (Greeter)super.getPort(SOAPPORTTEST2, Greeter.class);
    }

}
