/* Generated by WSDLToJava Compiler. */

package org.objectweb.celtix.ws.rm.wsdl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the Celtix 0.5-SNAPSHOT
 * Wed Feb 15 09:47:08 GMT 2006
 * Generated source version: 0.5-SNAPSHOT
 * 
 */

@WebService(wsdlLocation = "C:/celtix/working-copies/andrea/celtix-api/src/main/resources/wsdl/wsrm.wsdl", 
            targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/rm/wsdl", 
            name = "SequenceAbstractPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE, 
             use = SOAPBinding.Use.LITERAL, 
             style = SOAPBinding.Style.DOCUMENT)

public interface SequenceAbstractPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/rm", 
               name = "CreateSequenceResponse")
    @WebMethod(operationName = "CreateSequence")
    org.objectweb.celtix.ws.rm.CreateSequenceResponseType createSequence(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/rm",  
                  name = "CreateSequence")
        org.objectweb.celtix.ws.rm.CreateSequenceType create
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "TerminateSequence")
    void terminateSequence(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2005/02/rm",  
                  name = "TerminateSequence")
        org.objectweb.celtix.ws.rm.TerminateSequenceType terminate
    );
}