
package org.objectweb.hello_world_doc_wrapped_bare;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BadRecordLit", targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
public class BadRecordLitFault
    extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private String faultInf;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BadRecordLitFault(String message, String faultInfo) {
        super(message);
        this.faultInf = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public BadRecordLitFault(String message, String faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInf = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.String
     */
    public String getFaultInfo() {
        return faultInf;
    }

}
