
package org.objectweb.hello_world_doc_wrapped_bare;

import javax.xml.ws.WebFault;
import org.objectweb.hello_world_doc_wrapped_bare.types.NoSuchCodeLit;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "NoSuchCodeLit", targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare/types")
public class NoSuchCodeLitFault
    extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchCodeLit faultInf;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchCodeLitFault(String message, NoSuchCodeLit faultInfo) {
        super(message);
        faultInf = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public NoSuchCodeLitFault(String message, NoSuchCodeLit faultInfo, Throwable cause) {
        super(message, cause);
        faultInf = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.objectweb.hello_world_doc_wrapped_bare.types.NoSuchCodeLit
     */
    public NoSuchCodeLit getFaultInfo() {
        return faultInf;
    }

}
