
package org.objectweb.hello_world_doc_wrapped_bare;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SOAPService", 
                  targetNamespace = "http://objectweb.org/hello_world_doc_wrapped_bare", 
                  wsdlLocation = "hello_world_doc_wrapped_bare.wsdl")
public class SOAPService
    extends Service {

    private  static final URL WSDL_LOCATION;
    private  static final QName SOAPSERVICE = 
        new QName("http://objectweb.org/hello_world_doc_wrapped_bare", "SOAPService");
    private  static final QName SOAPPORT = 
        new QName("http://objectweb.org/hello_world_doc_wrapped_bare", "SoapPort");

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Project/jaxws-2.0ea2/bin/hello_world_doc_wrapped_bare.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SOAPSERVICE);
    }

    /**
     * 
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "SoapPort")
    public Greeter getSoapPort() {
        return (Greeter)super.getPort(SOAPPORT, Greeter.class);
    }

}
