<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://cxf.apache.org/DiffPortTypeNs/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DiffPortTypeNs"
    xmlns:n1="http://cxf.apache.org/DiffPortTypeNs-Import/"
    targetNamespace="http://cxf.apache.org/DiffPortTypeNs/">
    <wsdl:import namespace="http://cxf.apache.org/DiffPortTypeNs-Import/"
        location="DiffPortTypeNs-Import.wsdl" />

    <wsdl:binding name="DiffPortTypeNsSOAP" type="n1:DiffPortTypeNs">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="NewOperation">
            <soap:operation soapAction="http://cxf.apache.org/DiffPortTypeNs/NewOperation" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DiffPortTypeNs">
        <wsdl:port binding="tns:DiffPortTypeNsSOAP" name="DiffPortTypeNsSOAP">
            <soap:address location="http://cxf.apache.org/DiffPortTypeNs/" />
        </wsdl:port>
    </wsdl:service>

    <wsdl:binding name="DiffPortTypeNsSOAPRpc" type="n1:DiffPortTypeNsRpc">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="NewOperationRpc">
            <soap:operation soapAction="http://cxf.apache.org/DiffPortTypeNs/NewOperationRpc" />
            <wsdl:input>
                <soap:body namespace="http://cxf.apache.org/DiffPortTypeNs-Import/" use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="http://cxf.apache.org/DiffPortTypeNs-Import/" use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DiffPortTypeNsRpc">
        <wsdl:port binding="tns:DiffPortTypeNsSOAPRpc" name="DiffPortTypeNsSOAPRpc">
            <soap:address location="http://cxf.apache.org/DiffPortTypeNsRpc/" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
