<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BaseService" targetNamespace="http://soapinterop.org/xsd"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://soapinterop.org/xsd"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsd1="http://soapinterop.org/xsd">
    <types>
        <schema targetNamespace="http://soapinterop.org/xsd"
            xmlns:tns="http://soapinterop.org/xsd"
            xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <element name="Foo">
                <complexType>
                    <choice>
                        <element name="Body" type="xsd:string"/>
                    </choice>
                </complexType>
            </element>
            <element name="FooResponse" type="xsd:string"/>
        </schema>
    </types>

    <message name="Foo">
        <part name="in" element="xsd1:Foo"/>
    </message>
    <message name="FooResponse">
        <part name="out" element="xsd1:FooResponse"/>
    </message>

    <portType name="InBandPortType">
        <operation name="Foo">
            <input name="Foo" message="tns:Foo"/>
            <output name="FooResponse" message="tns:FooResponse"/>
        </operation>
    </portType>

    <binding name="InBandPortBinding" type="tns:InBandPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <operation name="Foo">
            <soap:operation style="document"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="InBandService">
        <port name="InBandPort" binding="tns:InBandPortBinding">
            <soap:address location="http://localhost:8080/"/>
        </port>
    </service>
</definitions>