<?xml version="1.0" encoding="UTF-8"?>
<!-- Type coverage WSDL, contains examples of most types. -->
<definitions targetNamespace="http://schemas.iona.com/tests/dynamic_types"
         xmlns:tns="http://schemas.iona.com/tests/dynamic_types"
         xmlns="http://schemas.xmlsoap.org/wsdl/"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema"
         xmlns:xs="http://www.w3.org/2001/XMLSchema"
         xmlns:xsd1="http://soapinterop.org/xsd"
         xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
         xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
         xmlns:base="http://schemas.iona.com/tests/base">
    <types>
        <schema targetNamespace="http://schemas.iona.com/tests/dynamic_types"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
        <xsd:import namespace="http://schemas.iona.com/tests/base" schemaLocation="base.xsd"/>
            <!-- SimpleContent type -->
            <complexType name="Document">
                <simpleContent>
                  <extension base="base:Document">
                        <attribute name="ID" type="xsd:string" use="required"/>
                      </extension>
                </simpleContent>
              </complexType>
            </schema>
          </types>
          
</definitions>
