
package org.objectweb.celtix.tools.processors.java2;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/26/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Greeter",
            targetNamespace = "http://objectweb.org/hello_world_soap_http",
            wsdlLocation = "hello_world.wsdl")
public interface Greeter {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseType",
               targetNamespace = "http://objectweb.org/hello_world_soap_http/types")
    @RequestWrapper(localName = "sayHi",
                    targetNamespace = "http://objectweb.org/hello_world_soap_http/types",
                    className = "org.objectweb.celtix.tools.processors.java2.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse",
                     targetNamespace = "http://objectweb.org/hello_world_soap_http/types",
                     className = "org.objectweb.celtix.tools.processors.java2.types.SayHiResponse")
    String sayHi();


}
