//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="HelloWorldSOAPBinding", Namespace="http://objectweb.org/hello_world_soap_http")]
public class HelloWorldService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public HelloWorldService() {
        this.Url = "http://localhost:9000/HelloWorld";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("sayHiReturn", Namespace="http://objectweb.org/hello_world_soap_http")]
    public string sayHi() {
        object[] results = this.Invoke("sayHi", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsayHi(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sayHi", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsayHi(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("greetMeReturn", Namespace="http://objectweb.org/hello_world_soap_http")]
    public string greetMe([System.Xml.Serialization.XmlElementAttribute(Namespace="http://objectweb.org/hello_world_soap_http")] string greetMeParam) {
        object[] results = this.Invoke("greetMe", new object[] {
                    greetMeParam});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingreetMe(string greetMeParam, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("greetMe", new object[] {
                    greetMeParam}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgreetMe(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
