
package org.objectweb.hello_world_rpclit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SOAPServiceRPCLit", 
                  targetNamespace = "http://objectweb.org/hello_world_rpclit", 
                  wsdlLocation = "hello_world_rpc_lit.wsdl")
public class SOAPServiceRPCLit
    extends Service {

    private  static final URL WSDL_LOCATION;
    private  static final QName SOAPSERVICERPCLIT = 
        new QName("http://objectweb.org/hello_world_rpclit", "SOAPServiceRPCLit");
    private  static final QName SOAPPORTRPCLIT = 
        new QName("http://objectweb.org/hello_world_rpclit", "SoapPortRPCLit");

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Project/jaxws-2.0ea2/bin/hello_world_rpc_lit.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SOAPServiceRPCLit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPServiceRPCLit() {
        super(WSDL_LOCATION, SOAPSERVICERPCLIT);
    }

    /**
     * 
     * @return
     *     returns GreeterRPCLit
     */
    @WebEndpoint(name = "SoapPortRPCLit")
    public GreeterRPCLit getSoapPortRPCLit() {
        return (GreeterRPCLit)super.getPort(SOAPPORTRPCLIT, GreeterRPCLit.class);
    }

}
