<bindings
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    wsdlLocation="hello_world_jaxws_base.wsdl"
    xmlns="http://java.sun.com/xml/ns/jaxws">
    <bindings node="wsdl:definitions">
	<enableAsyncMapping>true</enableAsyncMapping>
	<bindings node="wsdl:portType[@name='GreeterAsync']">
	    <enableAsyncMapping>true</enableAsyncMapping>
	    <bindings node="wsdl:operation[@name='greetMeSometime']">
		<enableAsyncMapping>true</enableAsyncMapping>
	    </bindings>
	</bindings>
    </bindings>
</bindings>