package org.objectweb.hello_world_soap_http;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.objectweb.hello_world_soap_http.Greeter;
/**
 * This class was generated by the Celtix 1.1-SNAPSHOT
 * Tue Jul 25 11:51:44 GMT+08:00 2006
 * Generated source version: 1.1-SNAPSHOT
 * 
 */

@WebServiceClient(name = "SOAPService", targetNamespace = "http://objectweb.org/hello_world_soap_http", wsdlLocation = "file:/C:/celtix-install/celtix/samples/j2ee/jca/inbound_connection/wsdl/hello_world.wsdl")
public class SOAPService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://objectweb.org/hello_world_soap_http", "SOAPService");
    private final static QName SoapPort = new QName("http://objectweb.org/hello_world_soap_http", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/celtix-install/celtix/samples/j2ee/jca/inbound_connection/wsdl/hello_world.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SoapPort
     */
    @WebEndpoint(name = "SoapPort")
    public Greeter getSoapPort() {
        return (Greeter)super.getPort(SoapPort, Greeter.class);
    }

}