<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GreeterAsyncService" targetNamespace="http://apache.org/hello_world_async_soap_http" xmlns:ns1="http://apache.org/hello_world_async_soap_http" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://apache.org/hello_world_async_soap_http/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://apache.org/hello_world_async_soap_http/types" version="1.0">
<xs:element name="greetMeSometime">
<xs:complexType>
<xs:sequence>
<xs:element form="qualified" name="requestType" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="greetMeSometimeResponse">
<xs:complexType>
<xs:sequence>
<xs:element form="qualified" name="responseType" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://apache.org/hello_world_async_soap_http" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://apache.org/hello_world_async_soap_http">
<xsd:element name="greetMeSometime">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="requestType" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="greetMeSometimeResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="responseType" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="greetMeSometime">
    <wsdl:part name="greetMeSometime" element="ns2:greetMeSometime">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="greetMeSometimeResponse">
    <wsdl:part name="greetMeSometimeResponse" element="ns2:greetMeSometimeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="GreeterAsync">
    <wsdl:operation name="greetMeSometime">
      <wsdl:input name="greetMeSometime" message="ns1:greetMeSometime">
    </wsdl:input>
      <wsdl:output name="greetMeSometimeResponse" message="ns1:greetMeSometimeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GreeterAsyncServiceSoapBinding" type="ns1:GreeterAsync">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="greetMeSometime">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="greetMeSometime">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="greetMeSometimeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GreeterAsyncService">
    <wsdl:port name="GreeterAsyncPort" binding="ns1:GreeterAsyncServiceSoapBinding">
      <soap:address location="http://localhost:9090"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
