<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloWorld"
    targetNamespace="http://apache.org/hello_world" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:tns="http://apache.org/hello_world"
    xmlns:x1="http://apache.org/hello_world/types"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
        <schema
            targetNamespace="http://apache.org/hello_world/types" 
            xmlns="http://www.w3.org/2001/XMLSchema"
            xmlns:wsa="http://www.w3.org/2005/08/addressing"
            elementFormDefault="qualified">

            <import namespace="http://www.w3.org/2005/08/addressing" 
                    schemaLocation="ws-addr.xsd"/>

            <element name="sayHi" type="wsa:EndpointReferenceType"/>
            <element name="sayHiResponse">
                <complexType>
                    <sequence>
                        <element name="responseType" type="string"/>
                    </sequence>
                </complexType>
            </element>
        </schema>
    </wsdl:types>

    <wsdl:message name="sayHiRequest">
        <wsdl:part element="x1:sayHi" name="in"/>
    </wsdl:message>
    <wsdl:message name="sayHiResponse">
        <wsdl:part element="x1:sayHiResponse" name="out"/>
    </wsdl:message>
    
    <wsdl:portType name="Greeter">
        <wsdl:operation name="sayHi">
            <wsdl:input message="tns:sayHiRequest" name="sayHiRequest"/>
            <wsdl:output message="tns:sayHiResponse" name="sayHiResponse"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>

