<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://objectweb.org/xml_http_bare" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xformat="http://celtix.objectweb.org/bindings/xmlformat" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://objectweb.org/xml_http_bare" name="XMLOverHttp">
	<wsdl:types>
		<schema targetNamespace="http://objectweb.org/xml_http_bare" xmlns="http://www.w3.org/2001/XMLSchema">
			<element name="sayHiRequest" type="string"/>
			<element name="sayHiResponse" type="string"/>
		</schema>
	</wsdl:types>
	<message name="sayHiRequest">
		<part name="sayHiRequest" element="tns:sayHiRequest"/>
	</message>
	<message name="sayHiResponse">
		<part name="sayHiResponse" element="tns:sayHiResponse"/>
	</message>
	<portType name="GreetingPortType">
		<operation name="sayHello">
			<input name="sayHelloRequest" message="tns:sayHiRequest"/>
			<output name="sayHelloResponse" message="tns:sayHiResponse"/>
		</operation>
	</portType>
	<binding name="GreetingPortTypeXMLBinding" type="tns:GreetingPortType">
		<xformat:binding/>
		<operation name="sayHello">
			<input/>
			<output/>
		</operation>
	</binding>
	<service name="XMLoverHTTP">
	<port binding="tns:GreetingPortTypeXMLBinding" name="XMLPort">
	<http:address location="http://localhost:0/some_url"/>
	</port>
	</service>
</wsdl:definitions>
