<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:ns1="http://celtix.objectweb.org/routing/configuration" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="http://objectweb.org/HWRouter" 
	xmlns:tns1="http://objectweb.org/hello_world_doc_lit" 
	targetNamespace="http://objectweb.org/HWRouter" name="HWRouter">
	<import namespace="http://objectweb.org/hello_world_doc_lit" location="./hello_world_doc_lit.wsdl"/>
	
	<service name="HTTPSoapServiceSource">
		<port name="HTTPSoapPortSource" binding="tns1:Greeter_SOAPBinding">
			<soap:address location="http://localhost:9001"/>
		</port>
	</service>
	<service name="HTTPSoapServiceDestination">
		<port name="HTTPSoapPortDestination" binding="tns1:Greeter_SOAPBinding">
			<soap:address location="http://localhost:9002"/>
		</port>
	</service>
	
	<service name="HTTPXMLServiceSource">
		<port name="HTTPXMLPortSource" binding="tns1:Greeter_XMLBinding">
			<soap:address location="http://localhost:9003"/>
		</port>
	</service>
	
	<ns1:route name="route_0">
		<ns1:source port="HTTPSoapPortSource" service="tns:HTTPSoapServiceSource"/>
		<ns1:destination port="HTTPSoapPortDestination" service="tns:HTTPSoapServiceDestination"/>
	</ns1:route>
	<ns1:route name="route_1">
		<ns1:source port="HTTPXMLPortSource" service="tns:HTTPXMLServiceSource"/>
		<ns1:destination port="HTTPSoapPortDestination" service="tns:HTTPSoapServiceDestination"/>
	</ns1:route>	
</definitions>
