
package org.objectweb.hello_world_rpclit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import org.objectweb.hello_world_rpclit.types.MyComplexStruct;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-11/04/2005 09:41 AM(bbissett)
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GreeterRPCLit", 
            targetNamespace = "http://objectweb.org/hello_world_rpclit", 
            wsdlLocation = "hello_world_rpc_lit.wsdl")
@SOAPBinding(style = Style.RPC)
public interface GreeterRPCLit {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://objectweb.org/hello_world_rpclit", partName = "out")
    String sayHi();

    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://objectweb.org/hello_world_rpclit", partName = "out")
    String greetMe(
        @WebParam(name = "in", partName = "in")
        String in);

    /**
     * 
     * @param in
     * @return
     *     returns org.objectweb.hello_world_rpclit.types.MyComplexStruct
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://objectweb.org/hello_world_rpclit", partName = "out")
    MyComplexStruct sendReceiveData(
        @WebParam(name = "in", partName = "in")
        MyComplexStruct in);

}
