/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.cxf.systest.cxf993;

import testnotification.NotificationServicePort;

/**
 * This class was generated by the CXF 2.1-incubator-SNAPSHOT
 * Wed Sep 12 16:41:52 CST 2007
 * Generated source version: 2.1-incubator-SNAPSHOT
 * 
 */

public class Cxf993Impl implements NotificationServicePort {
    public String sendNotification(testnotification.SendNotification parameters) {
        return "dumy";
    }
}
